hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
          path: /uaa/**
          serviceId: auth-service
          url: http://localhost:5000
          stripPrefix: false
          sensitiveHeaders:
    user-service:
        path: /users/**
        serviceId: user-service
        stripPrefix: false
        sensitiveHeaders:

    lake-service:
        path: /lakes/**
        serviceId: lake-service
        stripPrefix: false
        sensitiveHeaders:
    lake-statistics-service:
        path: /statistics/**
        serviceId: lake-statistics-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
